=== Yagnesh874/xml/XML_4/Q4.XSD
<?xml version="1.0" encoding="UTF-8"?>
<Pujan:schema xmlns:Pujan="http://www.w3.org/2001/XMLSchema">
    <Pujan:element name="Employees">
        <Pujan:complexType>
            <Pujan:sequence>
                <Pujan:element name="Employee" maxOccurs="unbounded">
                    <Pujan:complexType>
                        <Pujan:sequence>
                            <Pujan:element name="EmployeeId" type="Pujan:string" />
                            <Pujan:element name="Name" type="Pujan:string" />
                            <Pujan:element name="Children">
                                <Pujan:complexType>
                                    <Pujan:choice maxOccurs="2">
                                        <Pujan:element name="Boy">
                                            <Pujan:complexType>
                                                <Pujan:sequence>
                                                    <Pujan:element name="Name" type="Pujan:string" />
                                                    <Pujan:element name="Birthdate" type="Pujan:date" />
                                                </Pujan:sequence>
                                            </Pujan:complexType>
                                        </Pujan:element>
                                        <Pujan:element name="Girl">
                                            <Pujan:complexType>
                                                <Pujan:sequence>
                                                    <Pujan:element name="Name" type="Pujan:string" />
                                                    <Pujan:element name="Birthdate" type="Pujan:date" />
                                                </Pujan:sequence>
                                            </Pujan:complexType>
                                        </Pujan:element>
                                    </Pujan:choice>
                                </Pujan:complexType>
                            </Pujan:element>
                        </Pujan:sequence>
                    </Pujan:complexType>
                </Pujan:element>
            </Pujan:sequence>
        </Pujan:complexType>
    </Pujan:element>
</Pujan:schema>

=== Yagnesh874/xml/XML_4/Q4.XML
<?xml version="1.0" encoding="UTF-8"?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Q4.XSD">
    <Employee>
        <EmployeeId>A-84</EmployeeId>
        <Name>Pujan Saraniya</Name>
        <Children>
            <Boy>
                <Name>XYZ Saraniya</Name>
                <Birthdate>2030-09-15</Birthdate>
            </Boy>
            <Girl>
                <Name>XYZ Saraniya</Name>
                <Birthdate>2030-05-12</Birthdate>
            </Girl>
        </Children>
    </Employee>
    <Employee>
        <EmployeeId></EmployeeId>
        <Name>Pujan Saraniya</Name>
        <Children>
            <Boy>
                <Name>XYZ Saraniya</Name>
                <Birthdate>2030-11-20</Birthdate>
            </Boy>
            <Girl>
                <Name>XYZ Saraniya</Name>
                <Birthdate>2030-05-12</Birthdate>
            </Girl>
        </Children>
    </Employee>
</Employees>
