=== Yagnesh874/xml/XML_4/Q5.XSD
<?xml version="1.0" encoding="UTF-8"?>
<Pujan:schema xmlns:Pujan="http://www.w3.org/2001/XMLSchema">
    <Pujan:element name="Salespeople">
        <Pujan:complexType>
            <Pujan:sequence>
                <Pujan:element name="Salesperson" maxOccurs="unbounded">
                    <Pujan:complexType>
                        <Pujan:sequence>
                            <Pujan:element name="Name" type="Pujan:string" />
                            <Pujan:element name="BusinessInfo">
                                <Pujan:complexType>
                                    <Pujan:sequence>
                                        <Pujan:element name="Company" type="Pujan:string" />
                                        <Pujan:element name="Department">
                                            <Pujan:simpleType>
                                                <Pujan:restriction base="Pujan:string">
                                                    <Pujan:enumeration value="Sales" />
                                                    <Pujan:enumeration value="Financial" />
                                                    <Pujan:enumeration value="Operation" />
                                                    <Pujan:enumeration value="Database" />
                                                </Pujan:restriction>
                                            </Pujan:simpleType>
                                        </Pujan:element>
                                        <Pujan:element name="Manager" type="Pujan:string" />
                                        <Pujan:element name="PhoneNo" type="Pujan:string" />
                                        <Pujan:element name="Email" type="Pujan:string" />
                                    </Pujan:sequence>
                                </Pujan:complexType>
                            </Pujan:element>
                            <Pujan:element name="PersonalInfo">
                                <Pujan:complexType>
                                    <Pujan:sequence>
                                        <Pujan:element name="PhoneNo" type="Pujan:string" />
                                        <Pujan:element name="Address" type="Pujan:string" />
                                    </Pujan:sequence>
                                </Pujan:complexType>
                            </Pujan:element>
                        </Pujan:sequence>
                    </Pujan:complexType>
                </Pujan:element>
            </Pujan:sequence>
        </Pujan:complexType>
    </Pujan:element>
</Pujan:schema>

=== Yagnesh874/xml/XML_4/Q5.XML
<?xml version="1.0" encoding="UTF-8"?>
<Salespeople xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Q5.XSD">
    <Salesperson>
        <Name>XYZ Saraniya</Name>
        <BusinessInfo>
            <Company>Compounders</Company>
            <Department>Financial</Department>
            <Manager>Pujan Saraniya</Manager>
            <PhoneNo>+919316534408</PhoneNo>
            <Email>pujansaraniya@compounders.co.in</Email>
        </BusinessInfo>
        <PersonalInfo>
            <PhoneNo>+919316534408</PhoneNo>
            <Address>Navrangpura , Ahmedabad</Address>
        </PersonalInfo>
    </Salesperson>
</Salespeople>
