=== Yagnesh874/xml/XML_4/Q6.XSD
<?xml version="1.0" encoding="UTF-8"?>
<Pujan:schema xmlns:Pujan="http://www.w3.org/2001/XMLSchema">
    <Pujan:element name="Employees">
        <Pujan:complexType>
            <Pujan:sequence>
                <Pujan:element name="Employee" maxOccurs="unbounded">
                    <Pujan:complexType>
                        <Pujan:sequence>
                            <Pujan:element name="EmployeeNumber" type="Pujan:string" />
                            <Pujan:element name="Name" type="Pujan:string" />
                            <Pujan:element name="Designation" type="Pujan:string" />
                            <Pujan:element name="Salary" type="Pujan:decimal" />
                        </Pujan:sequence>
                    </Pujan:complexType>
                </Pujan:element>
            </Pujan:sequence>
        </Pujan:complexType>
    </Pujan:element>
</Pujan:schema>

=== Yagnesh874/xml/XML_4/Q6.XML
<?xml version="1.0" encoding="UTF-8"?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Q6.XSD">
    <Employee>
        <EmployeeNumber>A-84</EmployeeNumber>
        <Name>Pujan</Name>
        <Designation>Software Engineer</Designation>
        <Salary>80000.00</Salary>
    </Employee>
    <Employee>
        <EmployeeNumber>A-83</EmployeeNumber>
        <Name>Trushal</Name>
        <Designation>Marketing Manager</Designation>
        <Salary>95000.00</Salary>
    </Employee>
</Employees>
