=== Yagnesh874/xml/XML_4/Q7.XSD
<?xml version="1.0" encoding="UTF-8"?>
<Pujan:schema xmlns:Pujan="http://www.w3.org/2001/XMLSchema">
  <Pujan:element name="Items">
    <Pujan:complexType>
      <Pujan:sequence>
        <Pujan:element name="Item" maxOccurs="unbounded">
          <Pujan:complexType>
            <Pujan:sequence>
              <Pujan:element name="Name" type="Pujan:string" />
              <Pujan:element name="Category">
                <Pujan:simpleType>
                  <Pujan:restriction base="Pujan:string">
                    <Pujan:enumeration value="Chips" />
                    <Pujan:enumeration value="Biscuits" />
                    <Pujan:enumeration value="Salad" />
                    <Pujan:enumeration value="Bread" />
                  </Pujan:restriction>
                </Pujan:simpleType>
              </Pujan:element>
              <Pujan:element name="CompanyInfo">
                <Pujan:complexType>
                  <Pujan:sequence>
                    <Pujan:element name="PhoneNo" type="Pujan:string" />
                    <Pujan:element name="Address" type="Pujan:string" />
                  </Pujan:sequence>
                </Pujan:complexType>
              </Pujan:element>
            </Pujan:sequence>
          </Pujan:complexType>
        </Pujan:element>
      </Pujan:sequence>
    </Pujan:complexType>
  </Pujan:element>
</Pujan:schema>

=== Yagnesh874/xml/XML_4/Q7.XML
<?xml version="1.0" encoding="UTF-8"?>
<Items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Q7.XSD">
    <Item>
        <Name>Potato Chips</Name>
        <Category>Chips</Category>
        <CompanyInfo>
            <PhoneNo>+919316534408</PhoneNo>
            <Address>Nehrunager , Ahmedabad</Address>
        </CompanyInfo>
    </Item>
    <Item>
        <Name>Chocolate Biscuits</Name>
        <Category>Biscuits</Category>
        <CompanyInfo>
            <PhoneNo>+919316534408</PhoneNo>
            <Address>Navrangpura  , Ahmedabad</Address>
        </CompanyInfo>
    </Item>
</Items>
