=== Yagnesh874/xml/XML_4/Q8.XSD
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Vendors">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Vendor" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string" />
                            <xs:element name="PersonalInfo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="PrimaryAddress" type="xs:string" />
                                        <xs:element name="SecondaryAddress" type="xs:string" minOccurs="0" />
                                        <xs:element name="Birthdate" type="xs:date" />
                                        <xs:element name="Gender">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Male" />
                                                    <xs:enumeration value="Female" />
                                                    <xs:enumeration value="Other" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Pincode" type="xs:positiveInteger" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Yagnesh874/xml/XML_4/Q8.XML
<?xml version="1.0" encoding="UTF-8"?>
<Vendors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Q8.XSD">
    <Vendor>
        <Name>Bharat Traders</Name>
        <PersonalInfo>
            <PrimaryAddress>Bopal , Ahmedabad</PrimaryAddress>
            <SecondaryAddress>28 , Bopal , Ahmedabad</SecondaryAddress>
            <Birthdate>2004-09-15</Birthdate>
            <Gender>Male</Gender>
            <Pincode>380008</Pincode>
        </PersonalInfo>
    </Vendor>
    <Vendor>
        <Name>Global Traders</Name>
        <PersonalInfo>
            <PrimaryAddress>Thaltej , Ahmedabad</PrimaryAddress>
            <Birthdate>2004-09-15</Birthdate>
            <Gender>Female</Gender>
            <Pincode>380007</Pincode>
        </PersonalInfo>
    </Vendor>
</Vendors>
